(function(){
'use strict';
const FIRST_KEY='wotw-wiki-age18-first-v3';
const SESSION_KEY='wotw-wiki-age18-v1';
const MERGE={styke:['psy-styke','dreierkonstellation','bogen-styke','intim-styke','intim-styke-vesper','intim-styke-valeria','anatomie-styke'],vesper:['psy-vesper','dreierkonstellation','bogen-vesper','intim-vesper','intim-styke-vesper','intim-vesper-valeria','anatomie-vesper'],valeria:['psy-valeria','dreierkonstellation','bogen-valeria','intim-valeria','intim-styke-valeria','intim-vesper-valeria','anatomie-valeria'],kaitlyn:['intim-kaitlyn','intim-kaitlyn-korruption','anatomie-kaitlyn'],tacitus:['anatomie-tacitus'],elise:['intim-elise'],tamsin:['intim-tamsin','anatomie-tamsin'],mara:['intim-mara'],ellyn:['intim-ellyn']};
const PARENT={};Object.entries(MERGE).forEach(([parent,ids])=>ids.forEach(id=>{if(!PARENT[id])PARENT[id]=parent;}));
const HIDDEN=new Set(Object.values(MERGE).flat());
const PRIVATE_ART={vesper:{src:'assets/vesper-candlelight.png',title:'Vesper – private Charakterstudie',caption:'Das rote Buch liegt in Reichweite. Die Ruhe ist dieselbe wie im Studierzimmer, nur ohne die öffentliche Schicht darüber.'},valeria:{src:'assets/valeria-private-night.webp',title:'Valeria – private Charakterstudie',caption:'Rüstung und Schwert sind abgelegt. Die Haltung nicht.'},kaitlyn:{src:'assets/kaitlyn-private-v2.webp',title:'Kaitlyn – private Charakterstudie',caption:'Hinter der gesellschaftlichen Fassade: rote Seide, Spiegel und eine Frau, die sich selbst beim Überschreiten alter Grenzen beobachtet.'},elise:{src:'assets/elise-private-raven.webp',title:'Elise – private Charakterstudie',caption:'Nähe ohne Leine: Elise bleibt auch in Ruhe vollständig Herrin über Haltung, Abstand und Entscheidung.'},tamsin:{src:'assets/tamsin-private.webp',title:'Tamsin – private Charakterstudie',caption:'Keine Boudoirpose: dieselbe robuste Frau, nur ohne Hof, Rüstung und Publikum.'},mara:{src:'assets/mara-private.webp',title:'Mara – private Charakterstudie',caption:'Wärme, Arbeit und selbstverständliche Körperlichkeit bleiben auch privat ihre Sprache.'},ellyn:{src:'assets/ellyn-private.webp',title:'Ellyn – private Charakterstudie',caption:'Eine ruhigere Form von Nähe: weniger Pose, mehr zögernde Neugier.'}};
Object.assign(ARTWORKS,{tiadora:[{src:'assets/tiadora-manor-v4.webp',alt:'Tiadora in schwarzer aristokratischer Kleidung auf der Treppe eines dunklen Herrenhauses mit versiegeltem Brief.',title:'Tiadora',caption:'Thorns Botin in ihrem eigenen Element: eine Treppe, ein Siegel und die Gewissheit, dass sie den Raum bereits beherrscht.'}],tamsin:[{src:'assets/tamsin-stableyard.webp',alt:'Tamsin Blackerly in einem winterlichen Stallhof.',title:'Tamsin Blackerly',caption:'Praktisch, wachsam und ohne höfische Politur: Tamsin gehört zwischen Holz, Stroh und Arbeit.'}],mara:[{src:'assets/mara-washhouse.webp',alt:'Mara Fenner im warmen Waschhaus.',title:'Mara Fenner',caption:'Mara in ihrer Welt: warmes Licht, nasse Arbeit und eine Frau, die Dienstbarkeit nicht mit Schwäche verwechselt.'}],ellyn:[{src:'assets/ellyn-serviceyard.webp',alt:'Ellyn Reed mit Wäschekorb im Diensthof.',title:'Ellyn Reed',caption:'Leiser als Mara, aber nicht unsichtbar: Ellyn zwischen Arbeit, Winterlicht und genauer Beobachtung.'}],elise:[{src:'assets/elise-raven-study.webp',alt:'Elise Zadaria mit Frost in einer verschneiten nordischen Landschaft.',title:'Elise Zadaria',caption:'Winter, alte Steine und Frost an ihrer Seite. Eine gefährliche Hexe und Anführerin, nicht bloß ein weiterer Schatten vor Balentyne.'}]});
const baseRefresh=refreshVisibleData,baseArticle=article,baseRoute=route;
window.removeEventListener('hashchange',baseRoute);
function accepted(){try{return localStorage.getItem(FIRST_KEY)==='confirmed'||sessionStorage.getItem(SESSION_KEY)==='confirmed';}catch(e){return !!adultUnlocked;}}
function persistAge(){try{localStorage.setItem(FIRST_KEY,'confirmed');sessionStorage.setItem(SESSION_KEY,'confirmed');}catch(e){}adultUnlocked=true;}
function showGate(target){document.body.classList.add('first-age-gate');document.title='Altersfreigabe | Der Nessische Knoten';const main=$('#main');main.innerHTML='<section class="first-gate-card"><div class="age-seal">18</div><div class="eyebrow">Der Nessische Knoten</div><h1>Dieses Kampagnenwiki ist für Erwachsene.</h1><p>Die Charakterakten enthalten neben Kampagnenchronik auch intime Körper- und Beziehungsdetails erwachsener fiktiver Figuren. Die Freigabe geschieht einmal beim ersten Besuch; danach liegen öffentliche und private Teile in derselben Akte.</p><form id="first-age-form"><label class="age-check"><input id="first-age-confirm" type="checkbox" required><span>Ich bin mindestens 18 Jahre alt und möchte das vollständige Wiki öffnen.</span></label><div class="actions"><button class="button primary" id="first-age-accept" type="submit" disabled>Wiki öffnen</button></div></form><p class="age-small">Lokale Selbstauskunft. Keine Ausweisdaten, keine Serverprüfung.</p></section>';const cb=$('#first-age-confirm'),btn=$('#first-age-accept');cb.onchange=()=>btn.disabled=!cb.checked;$('#first-age-form').onsubmit=e=>{e.preventDefault();if(!cb.checked)return;persistAge();document.body.classList.remove('first-age-gate');applyPatch();const dest=target&&target.startsWith('#/')?target:'#/start';if(location.hash===dest)newRoute();else location.hash=dest;};}
function mapId(id){return PARENT[id]||id;}
function isDossier(a){return !!a&&!a.adult&&['charaktere','personen'].includes(a.category);}
function flattenHtml(html){const root=document.createElement('div');root.innerHTML=html||'';root.querySelectorAll('h1,h2,h3').forEach(h=>{const p=document.createElement('p');p.className='dossier-sub';const s=document.createElement('strong');s.textContent=h.textContent.trim();p.appendChild(s);h.replaceWith(p);});root.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')||'';if(href.startsWith('#/artikel/')){const id=href.split('/').pop();if(PARENT[id])a.setAttribute('href','#/artikel/'+PARENT[id]);}if(['#/ab18','#/kategorie/intimitaet','#/kategorie/profile','#/kategorie/boegen','#/kategorie/charaktere','#/kategorie/personen'].includes(href))a.setAttribute('href','#/dossiers');});return root.innerHTML;}
function chunks(article){const root=document.createElement('div');root.innerHTML=article.body||'';const out=[];let current={title:'',nodes:[]};const push=()=>{if(current.title||current.nodes.length)out.push(current);current={title:'',nodes:[]};};Array.from(root.childNodes).forEach(n=>{if(n.nodeType===1&&/^H[1-3]$/.test(n.tagName)){push();current.title=n.textContent.trim();}else current.nodes.push(n.cloneNode(true));});push();return out;}
function chunkHtml(c){const box=document.createElement('div');c.nodes.forEach(n=>box.appendChild(n));let html=flattenHtml(box.innerHTML);if(c.title)html='<p class="dossier-sub"><strong>'+esc(c.title)+'</strong></p>'+html;return html;}
function classify(article,title){const t=norm((title||'')+' '+article.title+' '+article.id);if(article.category==='boegen')return 'stat';if(article.adult)return 'sexual';if(article.id==='dreierkonstellation')return 'relations';if(/erscheinung|aussehen|körper|silhouette|gesicht|haar|augen|stimme|anatom/.test(t))return 'appearance';if(/sexual|begehren|vorliebe|intim|körperakte|lust|orgasm|vulva|brüste/.test(t))return 'sexual';if(/bindung|beziehung|kontakt|freund|pakt|treue|affäre|dreier|nähe|vertrauen|liebe|loyal/.test(t))return 'relations';return 'bio';}
function collectDossier(a){const bins={bio:[],relations:[],appearance:[],sexual:[],stat:[]};const srcs=[a,...(MERGE[a.id]||[]).map(id=>RAW_BYID[id]).filter(Boolean)];srcs.forEach(src=>chunks(src).forEach(c=>{const k=classify(src,c.title),html=chunkHtml(c).trim();if(html)bins[k].push(html);}));return bins;}
function facts(a){const party=typeof PARTY!=='undefined'?PARTY.find(p=>p.id===a.id):null,rows=[];if(party?.sub)rows.push(['Klasse / Rolle',party.sub]);rows.push(['Typ',CATS[a.category]?.title||'Dossier']);if(a.status)rows.push(['Status',Array.isArray(a.status)?a.status.join(' · '):a.status]);if((a.aliases||[]).length)rows.push(['Auch bekannt als',a.aliases.slice(0,4).join(' · ')]);rows.push(['Kampagnenstand','1. Februar 4712 AR']);return '<div class="dossier-facts">'+rows.map(([k,v])=>'<div><span>'+esc(k)+'</span><strong>'+esc(v)+'</strong></div>').join('')+'</div>';}
function sectionBlock(title,items){return items.length?'<section class="dossier-section"><h2>'+title+'</h2>'+items.join('')+'</section>':'';}
function artFigure(x){return '<figure class="dossier-art"><img src="'+x.src+'" alt="'+esc(x.title)+'"><figcaption><strong>'+esc(x.title)+'</strong>'+esc(x.caption||'')+'</figcaption></figure>';}
function dossierArticle(a){const bins=collectDossier(a);let body=facts(a)+sectionBlock('Bio',bins.bio)+sectionBlock('Beziehungen',bins.relations)+sectionBlock('Aussehen',bins.appearance)+sectionBlock('Sexualität',bins.sexual);if(PRIVATE_ART[a.id])body+='<div class="private-second-art">'+artFigure(PRIVATE_ART[a.id])+'</div>';if(bins.stat.length)body+='<section class="dossier-stat"><h2>Statblock</h2><details><summary>Vollständigen Statblock öffnen</summary><div class="dossier-stat-body">'+bins.stat.join('')+'</div></details></section>';const mapLinks=arr=>[...new Set((arr||[]).map(mapId).filter(id=>id!==a.id&&RAW_BYID[id]&&!HIDDEN.has(id)))],sources=[...new Set([...(a.sources||[]),...(MERGE[a.id]||[]).flatMap(id=>RAW_BYID[id]?.sources||[])])];return baseArticle({...a,body,sources,links:mapLinks(a.links),backlinks:mapLinks(a.backlinks)});}
function patchedRefresh(){baseRefresh();const visibleArticles=DATA.articles.filter(a=>!HIDDEN.has(a.id)),seen=new Set(),mappedEdges=[];(DATA.edges||[]).forEach(e=>{const a=mapId(e.a),b=mapId(e.b);if(a===b||!RAW_BYID[a]||!RAW_BYID[b])return;const key=[a,b,e.type||'',e.label||''].join('|');if(seen.has(key))return;seen.add(key);mappedEdges.push({...e,a,b});});DATA={...DATA,articles:visibleArticles,edges:mappedEdges,categories:Object.fromEntries(Object.entries(DATA.categories).filter(([k])=>!['profile','boegen','intimitaet'].includes(k)))};ARTICLES=DATA.articles;BYID=Object.assign(Object.create(null),Object.fromEntries(ARTICLES.map(a=>[a.id,a])));CATS=DATA.categories;}
function patchedNavigation(){let out='<div class="nav-label">Die Kampagne</div>'+navItem('start','Am Spieltisch')+navItem('artikel/story-so-far','Die Geschichte bisher')+navItem('chronik','Chronik & Kalender',DATA.events.length);out+='<div class="nav-label">Figuren</div>'+navItem('dossiers','Dossiers',ARTICLES.filter(isDossier).length)+navItem('beziehungen','Beziehungsatlas',DATA.edges.length);out+='<div class="nav-label">Welt</div>'+navItem('kategorie/orte','Orte & Wege',ARTICLES.filter(a=>a.category==='orte').length)+navItem('kategorie/gruppen','Gruppen & Institutionen',ARTICLES.filter(a=>a.category==='gruppen').length)+navItem('kategorie/gegenstaende','Gegenstände',ARTICLES.filter(a=>a.category==='gegenstaende').length)+navItem('kategorie/welt','Setting & Weltwissen',ARTICLES.filter(a=>a.category==='welt').length);out+='<div class="nav-label">Nachschlagen</div>'+navItem('kategorie/vorhaben','Pläne & offene Fäden',ARTICLES.filter(a=>a.category==='vorhaben').length)+navItem('kategorie/faehigkeiten','Zauber & Fähigkeiten',ARTICLES.filter(a=>a.category==='faehigkeiten').length)+navItem('kategorie/regeln','Regeln',ARTICLES.filter(a=>a.category==='regeln').length);out+='<div class="nav-label">Mein Archiv</div>'+navItem('favoriten','Lesezeichen')+navItem('notizen','Eigene Notizen')+navItem('quellen','Quellen & Stand');$('#navigation').innerHTML=out;}
function dossiersPage(){const rows=ARTICLES.filter(isDossier).sort((a,b)=>a.title.localeCompare(b.title,'de'));return pageHead('Figuren','Dossiers','Eine Figur, eine Akte. Biografie, Beziehungen, Erscheinung, Sexualität und vorhandene Spielwerte liegen zusammen.')+'<div class="dossier-index">'+rows.map(a=>'<article class="card"><span class="eyebrow">'+esc(CATS[a.category]?.title||'Dossier')+'</span><h3><a href="#/artikel/'+a.id+'">'+esc(a.title)+'</a></h3><p>'+esc(a.summary||'')+'</p><div class="card-bottom"><span>'+(a.aliases?.length?esc(a.aliases[0]):'Kampagnenakte')+'</span><a href="#/artikel/'+a.id+'">Akte öffnen →</a></div></article>').join('')+'</div>';}
function markActive(path){document.querySelectorAll('.nav-link').forEach(a=>{const on=a.dataset.nav===path;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function newRoute(){if(!accepted()){showGate(location.hash||'#/start');return;}document.body.classList.remove('first-age-gate');adultUnlocked=true;const raw=location.hash.startsWith('#/')?location.hash.slice(2):'start',[path]=raw.split('?'),parts=path.split('/'),view=parts[0]||'start',id=parts[1];if(view==='artikel'&&PARENT[id]){location.replace('#/artikel/'+PARENT[id]);return;}if(view==='ab18'||(view==='kategorie'&&['charaktere','personen','profile','boegen','intimitaet'].includes(id))){location.replace('#/dossiers');return;}if(view==='dossiers'){$('#main').innerHTML=dossiersPage();document.title='Dossiers | Der Nessische Knoten';markActive('dossiers');window.scrollTo({top:0,left:0,behavior:'instant'});return;}baseRoute();if(view==='artikel'&&isDossier(BYID[id]))markActive('dossiers');}
function applyPatch(){adultUnlocked=true;refreshVisibleData=patchedRefresh;refreshVisibleData();navigation=patchedNavigation;article=function(a){return isDossier(a)?dossierArticle(a):baseArticle(a);};route=newRoute;navigation();}
if(!accepted())showGate(location.hash||'#/start');else{persistAge();applyPatch();newRoute();}
window.addEventListener('hashchange',newRoute);
})();
